TRUNCATE TABLE reviews RESTART IDENTITY CASCADE;
TRUNCATE TABLE offers RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;

INSERT INTO users (username, email, password, "userType", avatar, "createdAt", "updatedAt")
VALUES
  ('Max', 'max@example.com', '$2b$10$abcdefghijklmnopqrstuvABCDEFGHIJKLmnopqrstuvwxyz12', 'pro', '/static/avatar-max.jpg', NOW(), NOW()),
  ('Angelina', 'angelina@example.com', '$2b$10$abcdefghijklmnopqrstuvABCDEFGHIJKLmnopqrstuvwxyz34', 'pro', '/static/avatar-angelina.jpg', NOW(), NOW()),
  ('John', 'john@example.com', '$2b$10$abcdefghijklmnopqrstuvABCDEFGHIJKLmnopqrstuvwxyz56', 'normal', '/static/avatar-john.jpg', NOW(), NOW()),
  ('Sarah', 'sarah@example.com', '$2b$10$abcdefghijklmnopqrstuvABCDEFGHIJKLmnopqrstuvwxyz78', 'normal', '/static/avatar-sarah.jpg', NOW(), NOW()),
  ('Alex', 'alex@example.com', '$2b$10$abcdefghijklmnopqrstuvABCDEFGHIJKLmnopqrstuvwxyz90', 'pro', '/static/avatar-alex.jpg', NOW(), NOW()),
  ('Kate', 'kate@example.com', '$2b$10$abcdefghijklmnopqrstuvABCDEFGHIJKLmnopqrstuvwxyzAB', 'normal', '/static/avatar-kate.jpg', NOW(), NOW());

INSERT INTO offers (
  title,
  description,
  "publishDate",
  city,
  "previewImage",
  photos,
  "isPremium",
  "isFavorite",
  rating,
  type,
  rooms,
  guests,
  price,
  features,
  "commentsCount",
  latitude,
  longitude,
  "authorId",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'Beautiful & luxurious studio at great location',
    'A quiet cozy and picturesque studio that hides behind a river by the unique lightness of Paris.',
    NOW(),
    'Paris',
    '/static/offer-paris-1.jpg',
    ARRAY[
      '/static/offer-paris-1-1.jpg',
      '/static/offer-paris-1-2.jpg',
      '/static/offer-paris-1-3.jpg'
    ],
    TRUE,
    TRUE,
    4.8,
    'apartment',
    3,
    4,
    120,
    ARRAY['Breakfast', 'Air conditioning', 'Laptop friendly workspace', 'Washer', 'Towels']::"enum_offers_features"[],
    2,
    48.8566,
    2.3522,
    1,
    NOW(),
    NOW()
  ),
  (
    'Cozy apartment in city center',
    'Cozy apartment in the very heart of Paris, close to main attractions and cafes.',
    NOW(),
    'Paris',
    '/static/offer-paris-2.jpg',
    ARRAY[
      '/static/offer-paris-2-1.jpg',
      '/static/offer-paris-2-2.jpg'
    ],
    FALSE,
    FALSE,
    4.2,
    'apartment',
    2,
    3,
    95,
    ARRAY['Air conditioning', 'Washer', 'Towels', 'Fridge']::"enum_offers_features"[],
    1,
    48.8584,
    2.2945,
    2,
    NOW(),
    NOW()
  ),
  (
    'Canal view house',
    'Spacious house with canal view, perfect for family stay in Amsterdam.',
    NOW(),
    'Amsterdam',
    '/static/offer-amsterdam-1.jpg',
    ARRAY[
      '/static/offer-amsterdam-1-1.jpg',
      '/static/offer-amsterdam-1-2.jpg'
    ],
    TRUE,
    TRUE,
    4.9,
    'house',
    4,
    6,
    200,
    ARRAY['Breakfast', 'Baby seat', 'Washer', 'Towels', 'Fridge']::"enum_offers_features"[],
    1,
    52.3676,
    4.9041,
    2,
    NOW(),
    NOW()
  ),
  (
    'Modern studio near river',
    'Modern studio with big windows and river view, perfect for couples.',
    NOW(),
    'Amsterdam',
    '/static/offer-amsterdam-2.jpg',
    ARRAY[
      '/static/offer-amsterdam-2-1.jpg',
      '/static/offer-amsterdam-2-2.jpg'
    ],
    FALSE,
    FALSE,
    4.3,
    'room',
    1,
    2,
    80,
    ARRAY['Washer', 'Towels', 'Fridge']::"enum_offers_features"[],
    0,
    52.3680,
    4.9030,
    3,
    NOW(),
    NOW()
  ),
  (
    'Historic house in old town',
    'Old but well renovated house in the very center of Cologne old town.',
    NOW(),
    'Cologne',
    '/static/offer-cologne-1.jpg',
    ARRAY[
      '/static/offer-cologne-1-1.jpg'
    ],
    TRUE,
    TRUE,
    4.7,
    'house',
    5,
    8,
    220,
    ARRAY['Breakfast', 'Washer', 'Towels', 'Fridge']::"enum_offers_features"[],
    1,
    50.9375,
    6.9603,
    4,
    NOW(),
    NOW()
  ),
  (
    'Business apartment near center',
    'Comfortable apartment suitable for business trips, with fast Wi-Fi and workspace.',
    NOW(),
    'Cologne',
    '/static/offer-cologne-2.jpg',
    ARRAY[
      '/static/offer-cologne-2-1.jpg'
    ],
    FALSE,
    FALSE,
    4.1,
    'apartment',
    1,
    2,
    90,
    ARRAY['Laptop friendly workspace', 'Washer', 'Fridge']::"enum_offers_features"[],
    0,
    50.9400,
    6.9650,
    5,
    NOW(),
    NOW()
  ),
  (
    'City center apartment',
    'Bright apartment in Brussels city center near main square.',
    NOW(),
    'Brussels',
    '/static/offer-brussels-1.jpg',
    ARRAY[
      '/static/offer-brussels-1-1.jpg'
    ],
    TRUE,
    FALSE,
    4.6,
    'apartment',
    2,
    4,
    130,
    ARRAY['Breakfast', 'Air conditioning', 'Washer', 'Towels']::"enum_offers_features"[],
    2,
    50.8503,
    4.3517,
    1,
    NOW(),
    NOW()
  ),
  (
    'Compact studio for weekend',
    'Small but cozy studio, good for short weekend trips.',
    NOW(),
    'Brussels',
    '/static/offer-brussels-2.jpg',
    ARRAY[
      '/static/offer-brussels-2-1.jpg'
    ],
    FALSE,
    TRUE,
    4.0,
    'room',
    1,
    2,
    70,
    ARRAY['Towels', 'Fridge']::"enum_offers_features"[],
    1,
    50.8520,
    4.3500,
    6,
    NOW(),
    NOW()
  ),
  (
    'Harbor view apartment',
    'Apartment with harbor view in Hamburg, close to public transport.',
    NOW(),
    'Hamburg',
    '/static/offer-hamburg-1.jpg',
    ARRAY[
      '/static/offer-hamburg-1-1.jpg'
    ],
    TRUE,
    TRUE,
    4.5,
    'apartment',
    3,
    5,
    150,
    ARRAY['Breakfast', 'Washer', 'Towels', 'Fridge']::"enum_offers_features"[],
    3,
    53.5511,
    9.9937,
    3,
    NOW(),
    NOW()
  ),
  (
    'Quiet suburb house',
    'House located in quiet suburb area of Hamburg, good for families.',
    NOW(),
    'Hamburg',
    '/static/offer-hamburg-2.jpg',
    ARRAY[
      '/static/offer-hamburg-2-1.jpg'
    ],
    FALSE,
    FALSE,
    4.2,
    'house',
    4,
    6,
    160,
    ARRAY['Baby seat', 'Washer', 'Towels']::"enum_offers_features"[],
    0,
    53.5600,
    9.9900,
    4,
    NOW(),
    NOW()
  ),
  (
    'Central hotel room',
    'Hotel room in the center of Dusseldorf close to shopping streets.',
    NOW(),
    'Dusseldorf',
    '/static/offer-dusseldorf-1.jpg',
    ARRAY[
      '/static/offer-dusseldorf-1-1.jpg'
    ],
    FALSE,
    TRUE,
    4.3,
    'hotel',
    1,
    2,
    110,
    ARRAY['Air conditioning', 'Towels', 'Fridge']::"enum_offers_features"[],
    1,
    51.2277,
    6.7735,
    2,
    NOW(),
    NOW()
  ),
  (
    'Spacious apartment with balcony',
    'Spacious apartment with big balcony and city view in Dusseldorf.',
    NOW(),
    'Dusseldorf',
    '/static/offer-dusseldorf-2.jpg',
    ARRAY[
      '/static/offer-dusseldorf-2-1.jpg'
    ],
    TRUE,
    FALSE,
    4.7,
    'apartment',
    3,
    5,
    170,
    ARRAY['Breakfast', 'Laptop friendly workspace', 'Washer', 'Towels', 'Fridge']::"enum_offers_features"[],
    0,
    51.2300,
    6.7800,
    5,
    NOW(),
    NOW()
  );

INSERT INTO reviews (
  text,
  "publishDate",
  rating,
  "authorId",
  "OfferId",
  "createdAt",
  "updatedAt"
)
VALUES
  ('A quiet cozy and picturesque studio, very friendly host and perfect location.', NOW(), 5, 1, 1, NOW(), NOW()),
  ('Nice place, but can be a bit noisy in the evening.', NOW(), 4, 3, 1, NOW(), NOW()),
  ('Great apartment with amazing view, everything was clean and well prepared.', NOW(), 5, 2, 2, NOW(), NOW()),
  ('Perfect house for a family trip, kids loved it, we will come back again.', NOW(), 5, 1, 3, NOW(), NOW()),
  ('Very good location, clean and comfortable.', NOW(), 4, 4, 2, NOW(), NOW()),
  ('Host was very helpful and responsive.', NOW(), 5, 5, 1, NOW(), NOW()),
  ('Nice historic house, but stairs are quite steep.', NOW(), 4, 6, 4, NOW(), NOW()),
  ('Good value for money.', NOW(), 4, 2, 5, NOW(), NOW()),
  ('Room is small but has everything you need.', NOW(), 4, 3, 8, NOW(), NOW()),
  ('Great harbor view and tasty breakfast.', NOW(), 5, 1, 9, NOW(), NOW()),
  ('Calm area, kids slept very well.', NOW(), 5, 4, 10, NOW(), NOW()),
  ('Hotel room is clean, staff is friendly.', NOW(), 4, 5, 11, NOW(), NOW()),
  ('Loved the balcony and city view.', NOW(), 5, 6, 12, NOW(), NOW()),
  ('Location is perfect for tourists.', NOW(), 5, 2, 7, NOW(), NOW()),
  ('Wi-Fi could be faster, but overall good stay.', NOW(), 3, 3, 6, NOW(), NOW());
